export const CATEGORIES_ACTION_TYPE = {
  FETCH_CATEGORIES_START: 'catrgory/FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'catrgory/FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILED: 'catrgory/FETCH_CATEGORIES_FAILED'
};
